Week5 [STEP 1] Rowan
yagom-academy/swift-starter-week5 pull request #23
Opened 2022-11-14 12:50 UTC by Kyeongjun2

@wongbingg 
안녕하세요 웡빙! 
STEP 1 PR 보내드립니다~~💪 이번 주도 피드백 잘 부탁드립니다 👏

# 고민한 점
## 타입 정의 파일 나누기
- class, enum, struct, protocol의 선언을 STEP1 파일을 새로 만들어 main과 별도로 작성해봤습니다.

## 프로토콜 프로퍼티
- 해당 프로토콜을 채택하는 타입에서 저장 프로퍼티 let을 사용하기 위해 프로토콜 정의할 때 읽기 전용으로 구현했습니다.

## 함수 분리
- 지난 주 미션에서 함수의 기능 분리에 미흡한 점이 있었습니다.
-  ```cast()``` 메서드를 정의할 때 기능 분리를 염두에 두고 작성했습니다. (합격자리스트에 추가, 합격자리스트에서 삭제, TalentedPerson 확인, TalentedPersonWithBadPersonality 확인, 합격자 안내)

## ```frequencyOfCursing``` Level에 따라 나눠보기
- BadPersonality protocol을 채택한 지원자를 확인할 때, frequencyOfCursing Level에 따라 합격 불합격 여부를 골라내기 위해 switch 구문을 사용해봤습니다.

## ```as?```
- 프로토콜 타입 캐스팅에 대한 이해가 아직 많이 부족한 것 같습니다.
- 이번 과제에서 passedApplicant Array는 Array<Person> 타입으로 지원자의 talent 프로퍼티를 확인하기 위해서 ```as?```를 통해 타입 캐스팅을 해줄 필요가 있었다고 생각합니다.
### commit 수정 전
- TalentedPerson / TalentedPersonWitBadPersonality 타입은 채용한 프로토콜이 달라서 따로 확인하는 절차를 만들었습니다.
- 결과는 잘 나오지만 타입 캐스팅으로 위 두 타입을 확인하는게 아니라 채용한 프로토콜이 있는지 확인함으로서 함수 표현이 더 간단해질 수 있을 것 같았습니다. -> 타입별로 talent 프로퍼티를 확인함
### commit 수정 후
- Protocol Talent, BadPersonality를 타입캐스팅하여 프로토콜 프로퍼티를 확인하는 조건으로 수정하였습니다.
- Talent 프로퍼티를 1회 확인하게 되어 보기 좋아진 것 같습니다.
- BadPersonality 프로퍼티를 확인하여 기준에 맞지 않으면 합격자 리스트에서 제거하는 형태로 바뀌었습니다.

--- 

이번 주도 화이팅입니다!!

2022-11-14 22:30 UTC, wongbingg commented
안녕하세요 로웬 님 Week5 STEP1 고생하셨습니다 ☺️

### [수행한 점]
- [x] PR 제목양식
- [x] PR 내용양식 
- [x] 정확한 브랜치에 PR 보내기
- [x] 학습도우미 태그하기
---
- [x] 요구된 타입이 정의되어 있는지
- [x] 프로토콜을 활용했는지
- [x] 합격자 명단 배열이 [Person] 타입인지



### ✅ 고민했던 점
- frequencyOfCursing level에 따라 나눠보기
    - 이 부분이 헷갈렸을 것 같아요. 요구사항에서 `그러나 실력이 뛰어나도 인성이 좋지않은 경우 합격 명단에서 제외됩니다.` 라는 것을 보았을 때, TalentedPersonWithBadPersonality 라는 타입 자체가 합격할 수 없어야할 것 같아요 ~!
    - 출력예시의 경우 그냥 예시로만 봐주시면 될 것 같아요~! (odong이 합격한 출력예시 때문에 헷갈리셨다면..)

전반적으로 잘 수행 해주셨네요 👍
나머지 부분들은 코드를 보고 코멘트 남겨두겠습니다 🧐

2022-11-14 23:35 UTC, wongbingg requested changes

2022-11-14 23:35 UTC, wongbingg commented on CodeStarterCamp_Week5/STEP1.swift
> +}
요구사항을 잘 적용 해주셨군요 👍

2022-11-14 23:35 UTC, wongbingg commented on CodeStarterCamp_Week5/STEP1.swift
> +}
64번줄 개행은 다른 곳과의 컨벤션에 맞지 않네요 🧐

2022-11-14 23:35 UTC, wongbingg commented on CodeStarterCamp_Week5/STEP1.swift
> +    }
기능분리를 잘 해주셨네요 👏 이렇게 처리하는 것도 물론 좋지만, 아쉽게 요구사항과 약간의 다른점이 있는 것 같아요
앞서 말씀 드렸던 것 처럼 `BadPersonality`를 채택하는 타입 자체를 걸러주는 것이 프로젝트 요구사항이라고 파악됩니다 🧐

2022-11-14 23:35 UTC, wongbingg commented on CodeStarterCamp_Week5/STEP1.swift
> +    }
기능분리를 잘 해놓으니 메인함수라고 볼 수 있는 `cast()` 가 어떤 기능을 하는지 단번에 파악이 가능해서 좋네요 👍

2022-11-14 23:35 UTC, wongbingg commented on CodeStarterCamp_Week5/main.swift
> +let wongbing = TalentedPerson(name: "wongbing", height: 185, singing: .A, dancing: .C, acting: .B)
제가 출연했군요 🤣🤣👍

2022-11-14 23:56 UTC, Kyeongjun2 commented on CodeStarterCamp_Week5/STEP1.swift
> +}
개행 삭제했습니다~!
코드를 썼다 지웠다 하면서 자꾸 마지막 중괄호 컨벤션이 맞지 않은 걸 놓치네요 🤦‍♂️

2022-11-14 23:57 UTC, Kyeongjun2 commented on CodeStarterCamp_Week5/STEP1.swift
> +    }
applicantList의 person 타입 인스턴스들이 ```BadPersonality``` 프로토콜 채택 여부에 따라 passedList에서 삭제하도록 메서드를 변경했습니다 👍

2022-11-15 11:33 UTC, wongbingg commented on CodeStarterCamp_Week5/STEP1.swift
> +    }
```suggestion
    mutating func checkBadPersonality(applicant: Person) {
        if applicant is BadPersonality {
            self.removeFromPassedList(applicant: applicant)
        }
    }
```

이렇게만 조건을 주어도 true / false 로 나뉘지 않을까요 ? 당연히 true 일 때만 if 문 안으로 들어 올 것입니다 ☺️

2022-11-15 11:34 UTC, wongbingg commented
수정사항이 잘 반영 되었네요 👍
이번 스텝에선 크게 고칠부분이 없이 잘 해주신 것 같습니다
다음 스텝도 화이팅입니다 !! 💪

2022-11-15 11:34 UTC, merged