Week5 [Step1] 송중
yagom-academy/swift-starter-week5 pull request #29
Opened 2022-11-16 11:17 UTC by kimseongj

@llingo 
안녕하세요 링고!! 벌써 Week5네요!! 벌써 5주가 지나갔다는게 믿기지가 않는군요! 이번 코드리뷰도 잘부탁드립니다!! 

## 조언이 필요한 점
### 다운캐스팅할 때 프로토콜이란?
다른분이 작성하신 코드를 봤는데 Person타입을 Talent 프로토콜로 다운캐스팅하더라구요!
제가 공부했던 내용은 자기 자신을 상속받은 자식클래스로만 다운캐스팅이 가능한 줄 알았는데 어떻게 이게 가능한가요??🧐

2022-11-16 12:39 UTC, llingo requested changes
안녕하세요 @kimseongj 님!
마지막 주차의 첫번째 PR 축하드립니다 🎉

이번 스텝에서 학습할 핵심 경험은 다음과 같습니다.
- [x] Protocol을 생성하고 채택할 수 있는지
- [x] Protocol에 적절한 저장 프로퍼티를 정의하고, 이를 타입 내부에서 구현하고 있는지
- [x] 타입 캐스팅을 활용해, 프로토콜을 채택하고 있는 타입을 검사할 수 있는지

남겨드린 코멘트 확인하시고 수정 부탁드립니다 :) 수정 후 DM이나 멘션 남겨주시면 바로 확인하겠습니다!

---

**Q1. 상속받은 자식클래스로만 다운캐스팅이 가능한 줄 알았는데 어떻게 이게 가능한가요? 🧐**
A. Person 배열에 있는 인스턴스가 해당 프로토콜을 채택했는지도 확인이 가능하기 때문입니다! `as?` 로 캐스팅하게 되면 만약, 다운 캐스팅이 실패할 경우 nil이 됩니다!

2022-11-16 12:39 UTC, seu0313 commented on CodeStarterCamp_Week5/Protocol.swift
> +}
파일 이름은 Protocol.swift 로 하는 것보단 Protocol 폴더를 구성하고 각각의 프로토콜, 열거형 타입을 각각의 파일로 구분하는 것도 좋을 것 같아요!

2022-11-16 12:39 UTC, seu0313 commented on CodeStarterCamp_Week5/TalentedPerson.swift
> +
불필요한 줄바꿈이 있는 것 같아요!

2022-11-16 12:39 UTC, llingo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +                if talentedWithBadPersonalityApplicant.singing == Level.A || talentedWithBadPersonalityApplicant.acting == Level.A || talentedWithBadPersonalityApplicant.dancing == Level.A && talente
singing, acting, dancing을 체크하는 함수를 프로토콜 기본 구현을 통해 구현할 수 있을 것 같아요!

2022-11-16 12:39 UTC, llingo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +            if let talentedWithBadPersonalityApplicant = applicant as? TalentedPersonWithBadPersonality {
인스턴스가 해당 타입을 상속, 채택하고 있는지 `is` 타입 Checking을 통해서도 확인할 수 있을 것 같아요!

2022-11-16 12:39 UTC, llingo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +                if talentedApplicant.singing == Level.A || talentedApplicant.acting == Level.A || talentedApplicant.dancing == Level.A {
위에서 남겨드린 코멘트와 같이 위에서도 사용되므로 프로토콜 기본구현을 통해 구현해보시는 것을 추천합니다 :)

2022-11-17 10:09 UTC, kimseongj commented on CodeStarterCamp_Week5/AuditionManager.swift
> +                if talentedWithBadPersonalityApplicant.singing == Level.A || talentedWithBadPersonalityApplicant.acting == Level.A || talentedWithBadPersonalityApplicant.dancing == Level.A && talente
수정했습니다! 근데 링고가 의도한대로 제대로 수정된건지는 모르겠어요 😂

2022-11-17 10:30 UTC, kimseongj commented on CodeStarterCamp_Week5/AuditionManager.swift
> +            if let talentedWithBadPersonalityApplicant = applicant as? TalentedPersonWithBadPersonality {
is를 통해 타입 확인을 해도 아래에서 레벨이 a인지 b인지 c인지 확인하기 위해서는 as?를 써서 다운캐스팅을 해야되는게 맞는거겠죠?

2022-11-17 10:30 UTC, kimseongj commented on CodeStarterCamp_Week5/TalentedPerson.swift
> +
수정했씁니다!

2022-11-18 05:37 UTC, llingo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +                    }
프로토콜 기본구현을 사용하면 다음과 같이 활용해볼 수 있을 것 같아요

```swift
// Talent.swift

protocol Talent {
    var singing: Level { get }
    var dancing: Level { get }
    var acting: Level { get }

    func checkHighestLevel() -> Bool
}

extension Talent {
    func checkHighestLevel() -> Bool {
        return singing == .A || dancing == .A || acting == .A
    }
}
```

```swift
// AuditionManager.swift

// 개선 전
if talentedApplicant.singing == Level.A || talentedApplicant.acting == Level.A || talentedApplicant.dancing == Level.A {
    appendPassedList(applicant: applicant)
}

// 개선 후
if talentedApplicant.checkHighestLevel() {
    appendPassedList(applicant: applicant)
}
```

2022-11-18 05:37 UTC, llingo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +                    if talentedWithBadPersonalityApplicant.singing == Level.A || talentedWithBadPersonalityApplicant.acting == Level.A || talentedWithBadPersonalityApplicant.dancing == Level.A && tal
위에서 구현한 프로토콜 기본 구현을 사용할 수 있을 것 같아요 :)

2022-11-18 05:37 UTC, llingo commented on CodeStarterCamp_Week5/TalentedPerson.swift
> +    }
Indent가 맞지 않는 것 같아요!
만약, 가로 줄이 너무 길다면 다음과 같이 컨벤션을 줄 수 있을 것 같아요.

```swift
init(
    name: String,
    height: Int,
    singing: Level,
    dancing: Level,
    acting: Level
) {
    self.singing = singing
    self.dancing = dancing
    self.acting = acting
    super.init(name: name, height: height)
}
```

2022-11-18 05:37 UTC, llingo commented on CodeStarterCamp_Week5/Protocol/CheckTalent.swift
> +
이번 경우에는 CheckTalent 프로토콜을 생성하기 보단 Talent 프로토콜에 기본 구현을 사용하는 것이 좋을 것 같아요

2022-11-18 05:37 UTC, llingo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +            if let talentedWithBadPersonalityApplicant = applicant as? TalentedPersonWithBadPersonality {
네 :) 이번 경우는 체크하는 로직을 여러 곳에서 사용하고 있기 때문에 프로토콜 기본 구현을 통해 체크할 수 있을 것 같아요

2022-11-18 05:51 UTC, kimseongj commented on CodeStarterCamp_Week5/AuditionManager.swift
> +                    }
아하! 이런 방법이 있었군요!! 감사합니다!

2022-11-18 06:00 UTC, kimseongj commented
최종적으로 수정했습니다 감사합니다!

2022-11-18 06:12 UTC, llingo approved these changes
@kimseongj 님

스타터 캠프 5주동안 수고하셨습니다!! 🎉🎉🎉

2022-11-18 06:12 UTC, merged