Week5 [Step1] Zion
yagom-academy/swift-starter-week5 pull request #36
Opened 2023-03-20 08:14 UTC by LeeZion94

@jsa0224 

Step 1: 야곰 엔터 오디션

## 고민했던 점
### 타입캐스팅
cast 매서드 구현시 최대한 코드로만 봤엇을 때도 이해가 될 수 있게 타입캐스팅을 했습니다.
타입 캐스팅이 무분별하게 된다면 가독성이 떨어질 수 있는 코드가 될 수 있다고 생각합니다. 조건에 맞게 최대한 횟수를 줄이면서 구현했습니다.

2023-03-20 12:45 UTC, jsa0224 requested changes
안녕하세요, 시온님(@LeeZion94)~😊

벌써 5주차! 마지막 프로젝트네요!
이번 프로젝트 구현하신 거 보면서 전 프로젝트들보다 더 꼼꼼하게 구현해주신 게 느껴지네요!

코멘트는 아래에 남겨두겠습니다!

2023-03-20 12:45 UTC, jsa0224 commented on CodeStarterCamp_Week5/AuditionManager.swift
> +            }
```suggestion
        for applicant in totalApplicantsList {
            if let applicant = applicant as? Talent, applicant.isLevelA() == true {
                if applicant is TalentedPersonWithBadPersonality {
                   continue
                }
                
                passedApplicantsList.append(applicant as! Person)
            }
```
- 띄어쓰기가 안 되어 있네요!
- 21번 라인에서 강제 타입 캐스팅을 하셨네요! 
2주차 `Optional` 학습자료에서 `강제 옵셔널 바인딩`을 지양했던 것처럼, `강제 타입 캐스팅`도 지양합니다!
왜 강제로 옵셔널 바인딩이나 타입 캐스팅을 하면 안 되는지 찾아보셔도 좋을 거 같아요! 
- `totalApplicantsList`가 `Person` 타입의 배열이기 때문에, `Person` 타입이 아닌 객체가 들어가면 오류가 납니다.
따라서 `Person` 타입은 따로 `타입캐스팅`이 불필요해보여요!

2023-03-21 01:13 UTC, LeeZion94 commented on CodeStarterCamp_Week5/AuditionManager.swift
> +            }
넵! 강제 타입캐스팅을 불필요하게 하지 않는 방향으로 수정해둘게요!

2023-03-21 08:16 UTC, jsa0224 commented
수고하셨습니다, 시온님(@LeeZion94)!
5주차 미션까지 알차게 다 수행하실 수 있을 거 같네요!!
다음 스탭 진행하시면 됩니다👍

2023-03-21 08:17 UTC, merged