Week5 [STEP2] jeongmin(정민)
yagom-academy/swift-starter-week5 pull request #8
Opened 2022-05-11 14:55 UTC by jeongmin-l

@jaemuYeo 
안녕하세요 잼킹!
어느덧 마지막 PR을 드리게 되었습니다
코드 스타터 과정을 수료했다는 성취감도 들지만 이제 겨우 첫 발을 뗀 것이라는 생각도 들어 두려움도 듭니다 🥲
아직 부족한 점도 많고 넘어야 할 산도 많겠지만 열심히 공부해서 언젠가 잼킹처럼 실력있는 개발자가 되도록 노력하겠습니다 💪
5주간 감사했습니다! 😁

코드설명 드리겠습니다!
이전과 같은 부분은 제외하고 달라진 부분만 설명하겠습니다

# 코드설명
+ AuditionManager

## AuditionManager

### 프로퍼티
+ totalApplicantsList
  + 전체 지원자의 리스트를 읽기 전용으로 하기 위해서 private(set) 을 설정해 주었습니다.
+ passedApplicantsList
  + 합격한 지원자의 리스트를 외부에서 접근할 수 없고 내부에서만 사용할 수 있도록 private 설정하여 은닉했습니다

### 메서드
+ cast()
  + isBadPerson() -> Bool
  + isPassLevelTest -> Bool

지원자를 확인하는 반복문을 forEach문에서 for문으로 변경했습니다! 
for문의 where절을 사용해서 Talent를 채택하고 있는지 확인하기 위함입니다

#### 흐름설명
1. 지원자를 BadPersonality로 다운캐스팅해서 isBadPerson으로 인성이 좋지않은 경우(A등급 미만) 에는 true를, 좋은 경우에는 false를 반환받아 합격명단에서 제외할지 판단합니다.
2. 지원자를 Talent로 다운캐스팅 해서 LevelTest를 진행하는데 합격했다면 true, 불합격이라면 false를 반환해서 합격인 경우 지원자를 합격명단에 올립니다.

2022-05-12 08:37 UTC, jaemuYeo requested changes
정민님 스텝2도 고생많으셨습니다!!
마지막까지 완주하시느라 고생하셨습니다 👏
저도 실력있는 개발자는 아니지만 ,, 😅 정민님과 5주동안 함께 캠프롤 진행하면서
많이 공부하고, 최대한 제가 아는 모든 것들을 알려드리려고 노력했지만
아쉬움도 많이 남네요 ㅠㅠ 덕분에 저도 많은 도움이 됐어요!!
아직 하루가 남아 아쉬움이 남으니 머지는 살짝 뒤로 하고 한 가지만 더 추가해보아요 ㅎㅎ

1. `final` 키워드에 대해 알아보고 적용해보기
2. person파일에 있는 객체들을 분리하여 각 객체를 extension을 통해 프로토콜 채택해보기
(Person파일의 객체들은 각각의 파일로 분리되겠지만 또 하나의 그룹(폴더)로 묶을 수 있어요😀

2022-05-12 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +    private func isBadPerson(_ talentedApplicantWithBadPersonality: BadPersonality) -> Bool {
저번에 남겨드린 코멘트대로 기능분리를 해주셨군요!!
네이밍을 통해 Bool타입을 리턴한다는 것을 확실히 표현하셨네요 👍
멋져요!

2022-05-12 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +        for applicant in totalApplicantsList where applicant is Talent {
where절을 통해 타입캐스팅을 구현하셨네요!! 👏
where절을 잘 사용한다면 여러곳에서 가독성 좋은 코드를 만들 수 있답니다😀

2022-05-12 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week5/AuditionManager.swift
> +        if talentedApplicant.singing == Level.A || talentedApplicant.dancing == Level.A || talentedApplicant.acting == Level.A {
조건의 형태가 길어져서
```swift
if talentedApplicant.singing == Level.A ||
     talentedApplicant.dancing == Level.A ||
     talentedApplicant.acting == Level.A
{
     return true
} else {
     return false
}
```
이런식으로 분기해서 개행해주셔도 좋습니다!! 
정민님만의 컨벤션을 만들어 코드의 길이를 조절해보세요!

2022-05-12 08:37 UTC, jaemuYeo commented on CodeStarterCamp_Week5/AuditionManager.swift
>      func announcePassedApplicants() {
은닉화된 코드와 외부에서 사용되는 코드를 정리하면 좋을 것 같아요 😀

2022-05-12 09:00 UTC, jeongmin-l commented on CodeStarterCamp_Week5/AuditionManager.swift
> +    private func isBadPerson(_ talentedApplicantWithBadPersonality: BadPersonality) -> Bool {
감사합니다! 😁

2022-05-12 09:01 UTC, jeongmin-l commented on CodeStarterCamp_Week5/AuditionManager.swift
> +        for applicant in totalApplicantsList where applicant is Talent {
확실히 where절을 넣었더니 제가 읽기에도 훨씬 깔끔해진 느낌이라 좋았습니다 👍
다른 곳에서도 잘 써보겠습니다!

2022-05-12 09:02 UTC, corpiii commented on CodeStarterCamp_Week5/AuditionManager.swift
> +        if talentedApplicant.singing == Level.A || talentedApplicant.dancing == Level.A || talentedApplicant.acting == Level.A {
넵! 반영해보겠습니다

2022-05-12 09:03 UTC, jeongmin-l commented on CodeStarterCamp_Week5/AuditionManager.swift
>      func announcePassedApplicants() {
announcePassedApplicants 메서드를 가장 위로 올려보았습니다 ☺️

2022-05-12 11:45 UTC, jeongmin-l commented
final을 이용해서 클래스가 더이상 상속되지 않도록 지정했습니다! 😁

객체들을 분리하고 extension으로 프로토콜을 채택하게 두었는데 
Talent에는 singing, dancing, acting
BadPersonality에는 frequancyOfCursing
이렇게 프로토콜과 관련있는 프로퍼티 끼리 묶어주고 싶습니다.

하지만 extension의 프로퍼티는 계산 프로퍼티밖에 들어가지 않고 convenience init 밖에 해줄 수 없어서 
방법을 찾아보다가 결국은 프로퍼티들을 클래스 본체에 둘 수 밖에 없었는데요 
따로 표현하고 싶다면 띄어쓰기를 해서 표현해야 할까요? 🤔

2022-05-13 06:13 UTC, jaemuYeo commented
정민님 고생하셨습니다!!
class 객체의 extension 구현 중 발생한 이슈에 대해서는 사실 한 번 겪어보게 하고싶었어요!😀
그 외에 파일을 분리하고 class의 extension을 구현하는 방법은
실제 iOS프로젝트를 진행할떄에 딜리게이트 패턴 등의 구현에 자주 쓰이는 방식입니다!!
그냥 끝내기 아쉬워 추가로 드렸던 부분이니 너무 깊게 생각은 안하셔도 돼요☺️
5주 동안 너무나 고생많으셨고 다섯개의 프로젝트 완주하신 것에 대해 진심으로 축하드려요👏👏
마지막 머지 진행하겠습니다!!

2022-05-13 06:13 UTC, merged